# https://hub.docker.com/r/stefansundin/rbenv/
# docker build -f Dockerfile.rbenv.2.5.0 -t stefansundin/rbenv:2.5.0 .
# docker push stefansundin/rbenv:2.5.0
# docker run -i -t stefansundin/rbenv:2.5.0 bash

FROM ubuntu:16.04
MAINTAINER stefansundin https://github.com/stefansundin/dockerfiles

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
# rbenv and ruby-build dependencies
RUN apt-get install -y git curl build-essential
# install some gem dependencies
RUN apt-get install -y libreadline-dev libxml2-dev libxslt1-dev libpq-dev libsqlite3-dev libssl-dev

# install rbenv to /usr/local/rbenv
ENV RBENV_ROOT=/usr/local/rbenv
RUN git clone https://github.com/rbenv/rbenv.git $RBENV_ROOT
RUN git clone https://github.com/rbenv/ruby-build.git $RBENV_ROOT/plugins/ruby-build
RUN git clone https://github.com/rkh/rbenv-update.git $RBENV_ROOT/plugins/rbenv-update
ENV PATH $RBENV_ROOT/bin:$RBENV_ROOT/shims:$RBENV_ROOT/versions/2.5.0/bin:$PATH

# gem-rehash needs to be able to write to the shims directory
RUN mkdir $RBENV_ROOT/shims
RUN chmod 777 $RBENV_ROOT/shims

# we don't need gem documentation
RUN mkdir -p $RBENV_ROOT/versions/2.5.0/etc/
RUN echo 'gem: --no-document' >> $RBENV_ROOT/versions/2.5.0/etc/gemrc

# install ruby
RUN rbenv install 2.5.0
RUN rbenv global 2.5.0
RUN gem update --system

# put the app in /app
CMD mkdir /app
WORKDIR /app

# you may want to overwrite this in your Dockerfile
ENV APP_ENV=production
ENV RACK_ENV=deployment
ENV RAILS_ENV=production
